#from https://github.com/Kitware/vtk-ci-example/blob/master/.github/workflows/ci.yml
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - master
  schedule:
  # every two months"
  - cron: '0 0 1 */2 *'

jobs:
  build_and_test:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ v9.0, v9.1, v9.2, v9.3, v9.4, latest ]
    container: kitware/vtk-for-ci:${{ matrix.version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: 'source'
        fetch-depth: 0
        lfs: 'false'
        submodules: 'recursive'

    - name: Setup Directories
      working-directory: ${{github.workspace}}
      run: mkdir build

    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_PREFIX_PATH=/opt/vtk/install/ -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release ../source

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --parallel 2
